# \u8BBE\u7F6E\u6FC0\u6D3B\u7684\u73AF\u5883
spring:
  profiles:
    active: test
    quartz:
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true

# \u901A\u7528 Mapper \u914D\u7F6E
mapper:
  mappers: com.feida.common.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
# \u5206\u9875\u63D2\u4EF6\u914D\u7F6E
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql


