server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8

debug: true

logging:
  path: /home/feida/logs/nanerhuan/ams
  level:
    root: info
    tk:
      mybatis: TRACE
    org:
      springframework:
        boot:
          audoconfigure: info
    com:
      feida: debug
web:
  upload-path: D:/home/mapp/uploadFiles/attachment/event/video
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
      force-response: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-idle: 10
  redis4mq:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-idle: 10
        max-wait: 2000

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://120.79.10.144:3306/ams?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: GDFd@8707
    url: jdbc:mysql://localhost:3306/ams?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    initialSize: 100
    minIdle: 100
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: config,stat

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

